# Generated by Django 4.2.3 on 2023-07-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='valor',
            field=models.FloatField(default=0),
        ),
    ]
